export const uiComponentRegistry = [
  {name:'Animated Hero Section UI', source:'21st.dev', sourceUrl:'https://21st.dev/community/components/uniquesonu/animated-hero-section-ui/default', purpose:'Home hero reveal and subtle background lines', dependencies:['CSS'], reason:'Strong hierarchy with lightweight opacity/transform motion; adapted to ShadowTm tokens.'},
  {name:'Modern Hero Section', source:'21st.dev', sourceUrl:'https://21st.dev/community/components/uniquesonu/modern-hero-section-1/default', purpose:'Cursor-aware glow and layered hero depth', dependencies:['CSS'], reason:'Adapted the mouse-follow glow direction without copying implementation or adding a motion dependency; disabled for touch and reduced motion.'},
  {name:'Hero collection', source:'21st.dev', sourceUrl:'https://21st.dev/community/components/s/hero', purpose:'Split hero composition and product-first visual hierarchy', dependencies:['CSS','lucide-react'], reason:'Reviewed responsive, split and animated hero patterns; built a custom brand-specific composition.'},
  {name:'Navbar components', source:'21st.dev', sourceUrl:'https://21st.dev/community/components/s/navbar', purpose:'Responsive navigation reference', dependencies:['CSS'], reason:'Glass-on-scroll behavior without a heavy 3D dependency.'},
  {name:'Dashboard components', source:'21st.dev', sourceUrl:'https://21st.dev/community/components/s/dashboard', purpose:'Stats, sidebar and admin data layout', dependencies:['CSS','lucide-react'], reason:'Dense information layout adapted to the infrastructure theme.'},
  {name:'Pricing section collection', source:'21st.dev', sourceUrl:'https://21st.dev/community/components/s/pricing-section', purpose:'License term selector and plan comparison', dependencies:['CSS','lucide-react'], reason:'Clear recommended-plan hierarchy and feature comparison adapted without Tailwind or extra motion dependencies.'},
  {name:'Feature spotlight cards', source:'21st.dev', sourceUrl:'https://21st.dev/community/components/s/features', purpose:'Interactive configuration cards and product highlights', dependencies:['CSS'], reason:'Adapted the restrained spotlight-card direction using CSS variables and pointer-safe progressive enhancement.'},
  {name:'Animated components collection', source:'21st.dev', sourceUrl:'https://21st.dev/community/components/s/animated', purpose:'Entrance, tabs, buttons and state feedback', dependencies:['CSS'], reason:'Used lightweight transform and opacity patterns while omitting Framer Motion to keep the bundle lean.'},
  {name:'Animated Arrow Button', source:'21st.dev', sourceUrl:'https://21st.dev/community/components/originui/button/button-with-animated-arrow', purpose:'CTA arrow and hover choreography', dependencies:['CSS','lucide-react'], reason:'Adapted icon translation and restrained shine into the existing button primitive without Radix dependencies.'},
  {name:'Animated Navbar collection', source:'21st.dev', sourceUrl:'https://21st.dev/community/components/s/animated-navbar', purpose:'Scroll-aware glass header and active route indicator', dependencies:['CSS'], reason:'Adapted shrinking glass navigation, animated underline and mobile reveal patterns.'},
  {name:'Select collection', source:'21st.dev', sourceUrl:'https://21st.dev/community/components/s/select', purpose:'Configurator and checkout selection controls', dependencies:['CSS','lucide-react'], reason:'Adapted focus, chevron and selected-state patterns while retaining accessible native selects.'},
  {name:'Toast collection', source:'21st.dev', sourceUrl:'https://21st.dev/community/components/s/toast', purpose:'Admin success and error feedback', dependencies:['React','CSS'], reason:'Adapted a self-contained dismissible notification pattern rather than adding Sonner.'},
  {name:'Ruixen File Upload', source:'21st.dev', sourceUrl:'https://21st.dev/community/components/ruixenui/file-upload/default', purpose:'Admin PDF delivery upload', dependencies:['lucide-react','CSS'], reason:'Adapted file identity, drop-zone feedback and validation while keeping private backend storage.'},
  {name:'Footer collection', source:'21st.dev', sourceUrl:'https://21st.dev/community/components/s/footer', purpose:'Premium CTA, marquee and navigation footer', dependencies:['CSS'], reason:'Adapted large CTA and navigation-grid patterns into a lightweight branded footer.'},
  {name:'FAQ collection', source:'21st.dev', sourceUrl:'https://21st.dev/community/components/s/faq', purpose:'Accessible product and delivery FAQ', dependencies:['React','CSS'], reason:'Adapted a centered accordion pattern with native buttons and aria-expanded state.'},
  {name:'Custom product cards', source:'21st.dev inspiration', sourceUrl:'NOT FOUND', purpose:'Server and fund products', dependencies:['CSS'], reason:'No single source matched both compact specs and demo status needs; custom component created.'},
  {name:'Custom preloader', source:'21st.dev inspiration', sourceUrl:'NOT FOUND', purpose:'Initial application load', dependencies:['CSS'], reason:'A CSS-only reveal keeps the first load fast and respects reduced motion.'}
] as const;
