import 'dotenv/config';
import express from 'express'; import multer from 'multer'; import path from 'node:path'; import fs from 'node:fs/promises'; import {randomUUID} from 'node:crypto'; import {PrismaClient} from '@prisma/client';
const db=new PrismaClient(), app=express(), storage=path.resolve(process.env.PRIVATE_STORAGE_PATH??'storage/products'); await fs.mkdir(storage,{recursive:true});
app.use(express.json({limit:'1mb'}));
const upload=multer({storage:multer.diskStorage({destination:(_,__,cb)=>cb(null,storage),filename:(_,file,cb)=>cb(null,`${randomUUID()}.pdf`)}),limits:{fileSize:Number(process.env.MAX_PDF_BYTES??10485760)},fileFilter:(_,file,cb)=>cb(null,file.mimetype==='application/pdf'&&path.extname(file.originalname).toLowerCase()==='.pdf')});
function admin(req:express.Request,res:express.Response,next:express.NextFunction){if(!process.env.ADMIN_EMAIL||req.header('x-admin-email')!==process.env.ADMIN_EMAIL)return res.status(403).json({error:'Admin authorization required'});next()}
async function audit(event:string,orderId:number,userId:number,actor:string,metadata?:object){await db.auditLog.create({data:{event,orderId,userId,actor,metadata}})}
app.get('/api/payment-config',async(_req,res)=>{const settings=await db.paymentSettings.findFirst({select:{tronAddress:true,usdtTrc20Address:true}});res.json({tronAddress:settings?.tronAddress??null,usdtTrc20Address:settings?.usdtTrc20Address??null});});
app.post('/api/orders/:id/submit-payment',async(req,res)=>{const id=Number(req.params.id);const currency=req.body?.currency;const txHash=String(req.body?.txHash??'').trim();if(!['TRX','USDT_TRC20'].includes(currency)||txHash.length<8)return res.status(400).json({error:'Currency and transaction hash are required'});try{const settings=await db.paymentSettings.findFirst();const wallet=currency==='TRX'?settings?.tronAddress:settings?.usdtTrc20Address;if(!wallet)return res.status(409).json({error:'Payment wallet is not configured by admin'});const order=await db.order.update({where:{id},data:{status:'PAYMENT_REVIEW',paymentCurrency:currency,paymentWallet:wallet,txHash,paymentSubmittedAt:new Date()}});await audit('PAYMENT_SUBMITTED',id,order.userId,'user',{currency,txHash});res.json({order,status:'PAYMENT_REVIEW'});}catch(e){res.status(400).json({error:e instanceof Error?e.message:'Payment submission failed'})}});
app.get('/api/admin/payment-settings',admin,async(_req,res)=>res.json(await db.paymentSettings.findFirst()));
app.put('/api/admin/payment-settings',admin,async(req,res)=>{const tronAddress=req.body?.tronAddress?String(req.body.tronAddress).trim():null;const usdtTrc20Address=req.body?.usdtTrc20Address?String(req.body.usdtTrc20Address).trim():null;const current=await db.paymentSettings.findFirst();const saved=current?await db.paymentSettings.update({where:{id:current.id},data:{tronAddress,usdtTrc20Address}}):await db.paymentSettings.create({data:{tronAddress,usdtTrc20Address}});res.json(saved)});
app.post('/api/admin/orders/:id/approve-payment',admin,async(req,res)=>{const id=Number(req.params.id);try{const result=await db.$transaction(async tx=>{const order=await tx.order.findUnique({where:{id},include:{user:true,server:true,fund:true,delivery:true}});if(!order)throw new Error('Order not found');if(order.status!=='PAYMENT_REVIEW')throw new Error('Order must have a submitted payment for review');if(order.status==='PAYMENT_APPROVED'||order.delivery)return order;const product=order.server??order.fund;if(!product?.pdfPath||!product.emailSubject||!product.emailBody)throw new Error('Product delivery PDF and email template are INFORMATION NOT CONFIGURED');const now=new Date(), delay=(product as {deliveryDelayHours:number}).deliveryDelayHours??Number(process.env.DELIVERY_DELAY_HOURS??2), at=new Date(now.getTime()+delay*3600000);const updated=await tx.order.update({where:{id},data:{status:'DELIVERY_SCHEDULED',paymentApprovedAt:now,deliveryAt:at,deliveryEmail:order.user.email},include:{user:true}});await tx.emailDelivery.create({data:{orderId:id,userId:order.userId,email:order.user.email,pdfPath:product.pdfPath,emailSubject:product.emailSubject,emailBody:product.emailBody,scheduledFor:at}});return updated});await audit('PAYMENT_APPROVED',id,result.userId,'admin');await audit('DELIVERY_SCHEDULED',id,result.userId,'system',{scheduledFor:result.deliveryAt});res.json({order:result});}catch(e){res.status(400).json({error:e instanceof Error?e.message:'Approval failed'})}});
app.post('/api/admin/orders/:id/reject-payment',admin,async(req,res)=>{const id=Number(req.params.id);const order=await db.order.update({where:{id},data:{status:'PAYMENT_REJECTED'}});await audit('PAYMENT_REJECTED',id,order.userId,'admin');res.json({order})});
app.get('/api/orders/:id/delivery',async(req,res)=>{const delivery=await db.emailDelivery.findUnique({where:{orderId:Number(req.params.id)},select:{orderId: true,email:true,scheduledFor:true,status:true,attempts:true,sentAt:true,errorMessage:true}});if(!delivery)return res.status(404).json({error:'Delivery not found'});res.json(delivery)});
app.get('/api/admin/deliveries',admin,async(req,res)=>res.json(await db.emailDelivery.findMany({orderBy:{createdAt:'desc'},include:{order:{include:{user:true}}} })));
app.post('/api/admin/deliveries/:id/retry',admin,async(req,res)=>{const d=await db.emailDelivery.update({where:{id:Number(req.params.id)},data:{status:'RETRY',errorMessage:null}});await audit('DELIVERY_RETRIED',d.orderId,d.userId,'admin');res.json(d)});
async function attach(req:express.Request,res:express.Response){const id=Number(req.params.id);if(!req.file)return res.status(400).json({error:'Only PDF files are accepted'});const relative=path.relative(process.cwd(),req.file.path);const data={pdfPath:relative,emailSubject:String(req.body.emailSubject??''),emailBody:String(req.body.emailBody??'')};const target=req.path.includes('/servers/')?await db.server.update({where:{id},data}):await db.fundProduct.update({where:{id},data});res.json(target)}
app.post('/api/admin/products/:id/pdf',admin,upload.single('pdf'),attach);app.delete('/api/admin/products/:id/pdf',admin,async(req,res)=>{const id=Number(req.params.id);const product=req.path.includes('/servers/')?await db.server.findUnique({where:{id}}):await db.fundProduct.findUnique({where:{id}});if(product?.pdfPath)await fs.rm(path.resolve(product.pdfPath),{force:true});const updated=req.path.includes('/servers/')?await db.server.update({where:{id},data:{pdfPath:null}}):await db.fundProduct.update({where:{id},data:{pdfPath:null}});res.json(updated)});
app.listen(Number(process.env.PORT??4000),'0.0.0.0',()=>console.log(`API listening on ${process.env.PORT??4000}`));
