import 'dotenv/config';
import express from 'express'; import {sendAdminMessage} from './email.js'; import multer from 'multer'; import path from 'node:path'; import fs from 'node:fs/promises'; import {randomUUID} from 'node:crypto'; import {PrismaClient} from '@prisma/client';
const db=new PrismaClient(), app=express(), storage=path.resolve(process.env.PRIVATE_STORAGE_PATH??'storage/products'); await fs.mkdir(storage,{recursive:true});
app.use(express.json({limit:'1mb'}));
const upload=multer({storage:multer.diskStorage({destination:(_,__,cb)=>cb(null,storage),filename:(_,file,cb)=>cb(null,`${randomUUID()}.pdf`)}),limits:{fileSize:Number(process.env.MAX_PDF_BYTES??10485760)},fileFilter:(_,file,cb)=>cb(null,file.mimetype==='application/pdf'&&path.extname(file.originalname).toLowerCase()==='.pdf')});
function admin(req:express.Request,res:express.Response,next:express.NextFunction){if(!process.env.ADMIN_EMAIL||req.header('x-admin-email')!==process.env.ADMIN_EMAIL)return res.status(403).json({error:'Admin authorization required'});next()}
async function audit(event:string,orderId:number,userId:number,actor:string,metadata?:object){await db.auditLog.create({data:{event,orderId,userId,actor,metadata}})}
const supportAttempts=new Map<string,{count:number;reset:number}>();
app.post('/api/support/telegram',async(req,res)=>{try{const token=process.env.TELEGRAM_BOT_TOKEN,chatId=process.env.TELEGRAM_SUPPORT_CHAT_ID;if(!token||!chatId)throw new Error('Telegram support is INFORMATION NOT CONFIGURED');const ip=req.ip||'unknown',now=Date.now(),current=supportAttempts.get(ip);const rate=!current||current.reset<now?{count:0,reset:now+600000}:current;if(rate.count>=3)return res.status(429).json({error:'Please wait before sending another support request'});rate.count++;supportAttempts.set(ip,rate);const topic=String(req.body?.topic??'Support request').slice(0,80),contact=String(req.body?.contact??'Not provided').slice(0,120),orderId=String(req.body?.orderId??'Not provided').slice(0,80),message=String(req.body?.message??'').trim().slice(0,3000);if(message.length<10)return res.status(400).json({error:'Please provide at least 10 characters'});const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),8000);const response=await fetch(`https://api.telegram.org/bot${token}/sendMessage`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({chat_id:chatId,text:`New support request\nTopic: ${topic}\nContact: ${contact}\nOrder: ${orderId}\n\n${message}`}),signal:controller.signal});clearTimeout(timer);const result=await response.json() as {ok?:boolean;description?:string};if(!response.ok||!result.ok)throw new Error(result.description||'Telegram provider did not confirm the message');res.json({sent:true,provider:'telegram'});}catch(e){res.status(503).json({error:e instanceof Error?e.message:'Telegram support failed'})}});
app.get('/api/blockchain/tron/transaction/:hash',async(req,res)=>{const hash=String(req.params.hash??'').trim().toLowerCase();if(!/^[a-f0-9]{64}$/.test(hash))return res.status(400).json({error:'A valid 64-character TRON transaction hash is required'});try{const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),8000),headers:Record<string,string>={'Content-Type':'application/json'};if(process.env.TRONGRID_API_KEY)headers['TRON-PRO-API-KEY']=process.env.TRONGRID_API_KEY;const [transactionResponse,receiptResponse]=await Promise.all(['gettransactionbyid','gettransactioninfobyid'].map(method=>fetch(`https://api.trongrid.io/wallet/${method}`,{method:'POST',headers,body:JSON.stringify({value:hash}),signal:controller.signal})));clearTimeout(timer);if(!transactionResponse.ok||!receiptResponse.ok)throw new Error('TRON public API is unavailable');const transaction=await transactionResponse.json() as any,receipt=await receiptResponse.json() as any;if(!transaction?.txID)return res.status(404).json({found:false,error:'Transaction was not found on TRON mainnet'});res.json({found:true,hash:transaction.txID,confirmed:Boolean(receipt?.blockNumber),blockNumber:receipt?.blockNumber??null,timestamp:receipt?.blockTimeStamp??transaction?.raw_data?.timestamp??null,networkResult:receipt?.receipt?.result??transaction?.ret?.[0]?.contractRet??'INFORMATION NOT AVAILABLE',feeSun:receipt?.fee??null,contractType:transaction?.raw_data?.contract?.[0]?.type??'INFORMATION NOT AVAILABLE',explorerUrl:`https://tronscan.org/#/transaction/${hash}`,source:'TRON Grid'});}catch(e){res.status(503).json({error:e instanceof Error?e.message:'TRON lookup failed'})}});
app.post('/api/admin/messages',admin,async(req,res)=>{try{const to=String(req.body?.to??'').trim(),subject=String(req.body?.subject??'ShadowTm support'),text=String(req.body?.text??'');if(!to.includes('@')||!text) return res.status(400).json({error:'Recipient and message are required'});await sendAdminMessage(to,subject,text);res.json({sent:true});}catch(e){res.status(503).json({error:e instanceof Error?e.message:'SMTP send failed'})}});
app.get('/api/payment-config',async(_req,res)=>{const settings=await db.paymentSettings.findFirst({select:{tronAddress:true,usdtTrc20Address:true}});res.json({tronAddress:settings?.tronAddress??null,usdtTrc20Address:settings?.usdtTrc20Address??null});});
app.post('/api/orders/:id/submit-payment',async(req,res)=>{const id=Number(req.params.id);const currency=req.body?.currency;const txHash=String(req.body?.txHash??'').trim();if(!['TRX','USDT_TRC20'].includes(currency)||txHash.length<8)return res.status(400).json({error:'Currency and transaction hash are required'});try{const settings=await db.paymentSettings.findFirst();const wallet=currency==='TRX'?settings?.tronAddress:settings?.usdtTrc20Address;if(!wallet)return res.status(409).json({error:'Payment wallet is not configured by admin'});const order=await db.order.update({where:{id},data:{status:'PAYMENT_REVIEW',paymentCurrency:currency,paymentWallet:wallet,txHash,paymentSubmittedAt:new Date()}});await audit('PAYMENT_SUBMITTED',id,order.userId,'user',{currency,txHash});res.json({order,status:'PAYMENT_REVIEW'});}catch(e){res.status(400).json({error:e instanceof Error?e.message:'Payment submission failed'})}});
app.get('/api/admin/payment-settings',admin,async(_req,res)=>res.json(await db.paymentSettings.findFirst()));
app.put('/api/admin/payment-settings',admin,async(req,res)=>{const tronAddress=req.body?.tronAddress?String(req.body.tronAddress).trim():null;const usdtTrc20Address=req.body?.usdtTrc20Address?String(req.body.usdtTrc20Address).trim():null;const current=await db.paymentSettings.findFirst();const saved=current?await db.paymentSettings.update({where:{id:current.id},data:{tronAddress,usdtTrc20Address}}):await db.paymentSettings.create({data:{tronAddress,usdtTrc20Address}});res.json(saved)});
app.get('/api/admin/system-health',admin,async(_req,res)=>{let database=false;try{await db.$queryRaw`SELECT 1`;database=true}catch{}const smtp=['SMTP_HOST','SMTP_PORT','SMTP_USER','SMTP_PASSWORD','SMTP_FROM'].every(key=>Boolean(process.env[key]));let privateStorage=false;try{await fs.access(storage);privateStorage=true}catch{}res.json({api:true,database,smtp,privateStorage,telegram:Boolean(process.env.TELEGRAM_BOT_TOKEN&&process.env.TELEGRAM_SUPPORT_CHAT_ID),tronGrid:Boolean(process.env.TRONGRID_API_KEY),worker:'INFORMATION NOT AVAILABLE',checkedAt:new Date().toISOString()})});
app.get('/api/admin/orders',admin,async(_req,res)=>{const orders=await db.order.findMany({orderBy:{createdAt:'desc'},include:{user:{select:{id:true,email:true,firstName:true,lastName:true}},server:{select:{id:true,name:true,protocol:true}},fund:{select:{id:true,country:true,currency:true}},delivery:{select:{id:true,status:true,scheduledFor:true,sentAt:true,attempts:true,errorMessage:true}}}});res.json(orders)});
app.get('/api/admin/users',admin,async(_req,res)=>{const users=await db.user.findMany({orderBy:{createdAt:'desc'},select:{id:true,email:true,firstName:true,lastName:true,createdAt:true,_count:{select:{orders:true}}}});res.json(users)});
app.post('/api/admin/orders/:id/approve-payment',admin,async(req,res)=>{const id=Number(req.params.id);try{const result=await db.$transaction(async tx=>{const order=await tx.order.findUnique({where:{id},include:{user:true,server:true,fund:true,delivery:true}});if(!order)throw new Error('Order not found');if(order.status!=='PAYMENT_REVIEW')throw new Error('Order must have a submitted payment for review');if(order.status==='PAYMENT_APPROVED'||order.delivery)return order;const product=order.server??order.fund;if(!product?.pdfPath||!product.emailSubject||!product.emailBody)throw new Error('Product delivery PDF and email template are INFORMATION NOT CONFIGURED');const now=new Date(), delay=(product as {deliveryDelayHours:number}).deliveryDelayHours??Number(process.env.DELIVERY_DELAY_HOURS??2), at=new Date(now.getTime()+delay*3600000);const updated=await tx.order.update({where:{id},data:{status:'DELIVERY_SCHEDULED',paymentApprovedAt:now,deliveryAt:at,deliveryEmail:order.user.email},include:{user:true}});await tx.emailDelivery.create({data:{orderId:id,userId:order.userId,email:order.user.email,pdfPath:product.pdfPath,emailSubject:product.emailSubject,emailBody:product.emailBody,scheduledFor:at}});return updated});await audit('PAYMENT_APPROVED',id,result.userId,'admin');await audit('DELIVERY_SCHEDULED',id,result.userId,'system',{scheduledFor:result.deliveryAt});res.json({order:result});}catch(e){res.status(400).json({error:e instanceof Error?e.message:'Approval failed'})}});
app.post('/api/admin/orders/:id/reject-payment',admin,async(req,res)=>{const id=Number(req.params.id);const order=await db.order.update({where:{id},data:{status:'PAYMENT_REJECTED'}});await audit('PAYMENT_REJECTED',id,order.userId,'admin');res.json({order})});
app.get('/api/orders/:id/delivery',async(req,res)=>{const delivery=await db.emailDelivery.findUnique({where:{orderId:Number(req.params.id)},select:{orderId: true,email:true,scheduledFor:true,status:true,attempts:true,sentAt:true,errorMessage:true}});if(!delivery)return res.status(404).json({error:'Delivery not found'});res.json(delivery)});
app.get('/api/admin/deliveries',admin,async(req,res)=>res.json(await db.emailDelivery.findMany({orderBy:{createdAt:'desc'},include:{order:{include:{user:true,server:true,fund:true}}} })));
app.get('/api/admin/audit-logs',admin,async(req,res)=>{const limit=Math.min(Number(req.query.limit??100),250);res.json(await db.auditLog.findMany({orderBy:{createdAt:'desc'},take:limit,include:{order:{select:{id:true,status:true,type:true}}}}))});
app.post('/api/admin/deliveries/:id/retry',admin,async(req,res)=>{const d=await db.emailDelivery.update({where:{id:Number(req.params.id)},data:{status:'RETRY',errorMessage:null}});await audit('DELIVERY_RETRIED',d.orderId,d.userId,'admin');res.json(d)});
async function attach(req:express.Request,res:express.Response){const id=Number(req.params.id);if(!req.file)return res.status(400).json({error:'Only PDF files are accepted'});const relative=path.relative(process.cwd(),req.file.path);const data={pdfPath:relative,emailSubject:String(req.body.emailSubject??''),emailBody:String(req.body.emailBody??'')};const isServer=req.query.type==='server'; const target=isServer?await db.server.update({where:{id},data}):await db.fundProduct.update({where:{id},data});res.json(target)}
app.post('/api/admin/products/:id/pdf',admin,upload.single('pdf'),attach);app.delete('/api/admin/products/:id/pdf',admin,async(req,res)=>{const id=Number(req.params.id);const isServer=req.query.type==='server'; const product=isServer?await db.server.findUnique({where:{id}}):await db.fundProduct.findUnique({where:{id}});if(product?.pdfPath)await fs.rm(path.resolve(product.pdfPath),{force:true});const updated=isServer?await db.server.update({where:{id},data:{pdfPath:null}}):await db.fundProduct.update({where:{id},data:{pdfPath:null}});res.json(updated)});
app.listen(Number(process.env.PORT??4000),'0.0.0.0',()=>console.log(`API listening on ${process.env.PORT??4000}`));
