import fs from 'node:fs/promises';
import path from 'node:path';
import type {EmailDelivery,Order,User} from '@prisma/client';
import {renderTemplate} from './email.js';

function token(){const value=process.env.TELEGRAM_BOT_TOKEN;if(!value)throw new Error('Telegram bot is INFORMATION NOT CONFIGURED');return value}
async function call(method:string,body:Record<string,unknown>|FormData){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),12000);try{const options:RequestInit={method:'POST',body:body instanceof FormData?body:JSON.stringify(body),signal:controller.signal};if(!(body instanceof FormData))options.headers={'Content-Type':'application/json'};const response=await fetch(`https://api.telegram.org/bot${token()}/${method}`,options),result=await response.json() as {ok?:boolean;description?:string};if(!response.ok||!result.ok)throw new Error(result.description||`Telegram ${method} failed`);return result}finally{clearTimeout(timer)}}
export async function sendTelegramText(chatId:string,text:string){return call('sendMessage',{chat_id:chatId,text:text.slice(0,4096)})}
export async function sendTelegramOrderDelivery(chatId:string,delivery:EmailDelivery,order:Order&{user:User}){const data=(delivery.deliveryData&&typeof delivery.deliveryData==='object'&&!Array.isArray(delivery.deliveryData)?delivery.deliveryData:{}) as Record<string,unknown>,values={user_name:`${order.user.firstName} ${order.user.lastName??''}`.trim(),order_id:String(order.id),product_name:String(data.product_name??order.type),country:'INFORMATION NOT CONFIGURED',amount:String(order.price),order_date:order.createdAt.toISOString(),approved_at:order.paymentApprovedAt?.toISOString()??'INFORMATION NOT CONFIGURED',server_ip:String(data.server_ip??'INFORMATION NOT CONFIGURED'),server_port:String(data.server_port??'INFORMATION NOT CONFIGURED'),server_password:String(data.server_password??'INFORMATION NOT CONFIGURED'),license_key:String(data.license_key??'INFORMATION NOT CONFIGURED'),license_term:String(data.license_term??'INFORMATION NOT CONFIGURED')},message=renderTemplate(delivery.emailBody,values);
 if(delivery.pdfPath){const file=await fs.readFile(path.resolve(delivery.pdfPath)),form=new FormData();form.append('chat_id',chatId);form.append('caption',message.slice(0,1024));form.append('document',new Blob([new Uint8Array(file)],{type:'application/pdf'}),`ShadowTm-Order-${order.id}.pdf`);await call('sendDocument',form)}else await sendTelegramText(chatId,message);
}
