export interface Env { DB:D1Database; ADMIN_API_KEY:string; ALLOWED_ORIGINS?:string; TRONGRID_API_KEY?:string }
type Json=Record<string,unknown>;
const serverCatalog:Record<number,{name:string;price:number}>={1:{name:'SWIFT Banking Server',price:156},2:{name:'SEPA Processing Server',price:200},3:{name:'Fedwire Settlement Server',price:250},4:{name:'ACH Processing Server',price:210},5:{name:'TARGET2 Server',price:350}};
const fundPrices=[250,300,549,799,99,149,250,300,99,150,300,499,299,400,549,699,400,800,999,1299,750,199,299,499,899,1199,199,249,349,1400,499,999,450,500,1499,2299,229,399,590];
function cors(req:Request,env:Env){const origin=req.headers.get('Origin')||'',allowed=(env.ALLOWED_ORIGINS||'https://alixbot85-source.github.io').split(',').map(x=>x.trim());return {'Access-Control-Allow-Origin':allowed.includes(origin)?origin:allowed[0],'Vary':'Origin','Access-Control-Allow-Headers':'Content-Type, Authorization, X-Admin-Key','Access-Control-Allow-Methods':'GET, POST, PUT, OPTIONS','Access-Control-Max-Age':'86400'}}
function json(req:Request,env:Env,data:unknown,status=200){return new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store',...cors(req,env)}})}
function bytesToHex(bytes:Uint8Array){return [...bytes].map(x=>x.toString(16).padStart(2,'0')).join('')}
function randomToken(){const data=new Uint8Array(32);crypto.getRandomValues(data);return bytesToHex(data)}
async function passwordHash(password:string,salt:string){const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveBits']),bits=await crypto.subtle.deriveBits({name:'PBKDF2',hash:'SHA-256',salt:new TextEncoder().encode(salt),iterations:100000},key,256);return bytesToHex(new Uint8Array(bits))}
function validTronAddress(value:string){return /^T[1-9A-HJ-NP-Za-km-z]{33}$/.test(value)}
function admin(req:Request,env:Env){const supplied=req.headers.get('x-admin-key')||'';return Boolean(env.ADMIN_API_KEY)&&supplied.length===env.ADMIN_API_KEY.length&&supplied===env.ADMIN_API_KEY}
async function user(req:Request,env:Env){const token=(req.headers.get('Authorization')||'').replace(/^Bearer\s+/i,'');if(!token)return null;return env.DB.prepare(`SELECT u.id,u.email,u.first_name AS firstName,u.last_name AS lastName FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token=? AND s.expires_at>datetime('now')`).bind(token).first<any>()}
async function body(req:Request){try{return await req.json() as Json}catch{return {}}}
function product(type:string,id:number){if(type==='server')return serverCatalog[id]||null;if(type==='fund'){const price=fundPrices[id-1];return price?{name:`Resource package #${id}`,price}:null}if(type==='license'&&id>=1&&id<=5)return{name:`${id}-month application license`,price:id*50};return null}
async function audit(env:Env,event:string,orderId:number|null,userId:number|null,actor:string,metadata?:unknown){await env.DB.prepare('INSERT INTO audit_logs(event,order_id,user_id,actor,metadata) VALUES(?,?,?,?,?)').bind(event,orderId,userId,actor,metadata?JSON.stringify(metadata):null).run()}
async function route(req:Request,env:Env){const url=new URL(req.url),path=url.pathname;
 if(req.method==='OPTIONS')return new Response(null,{status:204,headers:cors(req,env)});
 if(path==='/api/health')return json(req,env,{api:true,database:true,platform:'cloudflare-workers-d1',checkedAt:new Date().toISOString()});
 if(path==='/api/payment-config'&&req.method==='GET'){const row=await env.DB.prepare('SELECT tron_address AS tronAddress,usdt_trc20_address AS usdtTrc20Address FROM payment_settings WHERE id=1').first();return json(req,env,row||{tronAddress:null,usdtTrc20Address:null})}
 if(path==='/api/auth/register'&&req.method==='POST'){const data=await body(req),email=String(data.email||'').trim().toLowerCase(),password=String(data.password||''),firstName=String(data.firstName||'').trim(),lastName=String(data.lastName||'').trim()||null;if(!email.includes('@')||password.length<8||!firstName)return json(req,env,{error:'Valid name, email, and password are required'},400);const salt=randomToken().slice(0,32),hash=await passwordHash(password,salt);try{const created=await env.DB.prepare('INSERT INTO users(email,first_name,last_name,password_hash,password_salt) VALUES(?,?,?,?,?) RETURNING id,email,first_name AS firstName').bind(email,firstName,lastName,hash,salt).first<any>(),token=randomToken(),expires=new Date(Date.now()+7*86400000).toISOString();await env.DB.prepare('INSERT INTO sessions(token,user_id,expires_at) VALUES(?,?,?)').bind(token,created.id,expires).run();return json(req,env,{user:created,token},201)}catch{return json(req,env,{error:'An account with this email may already exist'},409)}}
 if(path==='/api/auth/login'&&req.method==='POST'){const data=await body(req),email=String(data.email||'').trim().toLowerCase(),password=String(data.password||''),found=await env.DB.prepare('SELECT id,email,first_name AS firstName,last_name AS lastName,password_hash,password_salt FROM users WHERE email=?').bind(email).first<any>();if(!found||await passwordHash(password,found.password_salt)!==found.password_hash)return json(req,env,{error:'Email or password is incorrect'},401);const token=randomToken(),expires=new Date(Date.now()+7*86400000).toISOString();await env.DB.prepare('INSERT INTO sessions(token,user_id,expires_at) VALUES(?,?,?)').bind(token,found.id,expires).run();return json(req,env,{user:{id:found.id,email:found.email,firstName:found.firstName,lastName:found.lastName},token})}
 if(path==='/api/auth/me'&&req.method==='GET'){const current=await user(req,env);return current?json(req,env,{user:current}):json(req,env,{error:'Authentication required'},401)}
 if(path==='/api/auth/logout'&&req.method==='POST'){const token=(req.headers.get('Authorization')||'').replace(/^Bearer\s+/i,'');if(token)await env.DB.prepare('DELETE FROM sessions WHERE token=?').bind(token).run();return json(req,env,{signedOut:true})}
 if(path==='/api/orders/submit-payment'&&req.method==='POST'){const current=await user(req,env);if(!current)return json(req,env,{error:'Sign in before submitting a payment'},401);const data=await body(req),type=String(data.type||''),productId=Number(data.productId),currency=String(data.currency||''),txHash=String(data.txHash||'').trim().toLowerCase(),item=product(type,productId);if(!item||!['TRX','USDT_TRC20'].includes(currency)||!/^[a-f0-9]{64}$/.test(txHash))return json(req,env,{error:'Product, currency, or transaction hash is invalid'},400);const settings=await env.DB.prepare('SELECT tron_address,usdt_trc20_address FROM payment_settings WHERE id=1').first<any>(),wallet=currency==='TRX'?settings?.tron_address:settings?.usdt_trc20_address;if(!wallet)return json(req,env,{error:'Payment wallet is not configured by admin'},409);try{const created=await env.DB.prepare(`INSERT INTO orders(user_id,type,product_id,product_name,price,status,payment_currency,payment_wallet,tx_hash,configuration) VALUES(?,?,?,?,?,'PAYMENT_REVIEW',?,?,?,?) RETURNING *`).bind(current.id,type,productId,item.name,item.price,currency,wallet,txHash,JSON.stringify(data.configuration||{})).first<any>();await audit(env,'PAYMENT_SUBMITTED',created.id,current.id,'user',{currency,txHash});return json(req,env,{order:{id:created.id,status:created.status},status:'PAYMENT_REVIEW'},201)}catch{return json(req,env,{error:'This transaction hash has already been submitted'},409)}}
 const hashMatch=path.match(/^\/api\/blockchain\/tron\/transaction\/([a-fA-F0-9]{64})$/);if(hashMatch&&req.method==='GET'){const headers:Record<string,string>={'Content-Type':'application/json'};if(env.TRONGRID_API_KEY)headers['TRON-PRO-API-KEY']=env.TRONGRID_API_KEY;const hash=hashMatch[1].toLowerCase(),[txResponse,infoResponse]=await Promise.all(['gettransactionbyid','gettransactioninfobyid'].map(method=>fetch(`https://api.trongrid.io/wallet/${method}`,{method:'POST',headers,body:JSON.stringify({value:hash})})));if(!txResponse.ok||!infoResponse.ok)return json(req,env,{error:'TRON public API is unavailable'},503);const tx=await txResponse.json<any>(),info=await infoResponse.json<any>();if(!tx.txID)return json(req,env,{found:false,error:'Transaction was not found on TRON mainnet'},404);return json(req,env,{found:true,hash:tx.txID,confirmed:Boolean(info.blockNumber),blockNumber:info.blockNumber??null,timestamp:info.blockTimeStamp??tx.raw_data?.timestamp??null,networkResult:info.receipt?.result??tx.ret?.[0]?.contractRet??'INFORMATION NOT AVAILABLE',feeSun:info.fee??null,contractType:tx.raw_data?.contract?.[0]?.type??'INFORMATION NOT AVAILABLE',explorerUrl:`https://tronscan.org/#/transaction/${hash}`,source:'TRON Grid'})}
 if(path.startsWith('/api/admin/')){if(!admin(req,env))return json(req,env,{error:'Admin authorization required'},403);
  if(path==='/api/admin/system-health'&&req.method==='GET')return json(req,env,{api:true,database:true,smtp:false,privateStorage:false,tronGrid:Boolean(env.TRONGRID_API_KEY),worker:false,platform:'Cloudflare Workers + D1',checkedAt:new Date().toISOString()});
  if(path==='/api/admin/payment-settings'&&req.method==='GET'){const row=await env.DB.prepare('SELECT tron_address AS tronAddress,usdt_trc20_address AS usdtTrc20Address,updated_at AS updatedAt FROM payment_settings WHERE id=1').first();return json(req,env,row||null)}
  if(path==='/api/admin/payment-settings'&&req.method==='PUT'){const data=await body(req),tron=String(data.tronAddress||'').trim(),usdt=String(data.usdtTrc20Address||'').trim();if(!validTronAddress(tron)||!validTronAddress(usdt))return json(req,env,{error:'Valid TRON destination addresses are required'},400);await env.DB.prepare(`INSERT INTO payment_settings(id,tron_address,usdt_trc20_address,updated_at) VALUES(1,?,?,CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET tron_address=excluded.tron_address,usdt_trc20_address=excluded.usdt_trc20_address,updated_at=CURRENT_TIMESTAMP`).bind(tron,usdt).run();return json(req,env,{id:1,tronAddress:tron,usdtTrc20Address:usdt,updatedAt:new Date().toISOString()})}
  if(path==='/api/admin/orders'&&req.method==='GET'){const rows=await env.DB.prepare(`SELECT o.*,u.email,u.first_name,u.last_name FROM orders o JOIN users u ON u.id=o.user_id ORDER BY o.created_at DESC LIMIT 250`).all<any>();return json(req,env,rows.results.map(o=>({id:o.id,type:o.type,price:o.price,status:o.status,paymentCurrency:o.payment_currency,paymentWallet:o.payment_wallet,txHash:o.tx_hash,createdAt:o.created_at,user:{id:o.user_id,email:o.email,firstName:o.first_name,lastName:o.last_name},server:o.type==='server'?{name:o.product_name,protocol:'SERVER'}:undefined,fund:o.type==='fund'?{country:o.product_name,currency:'RESOURCE'}:undefined,delivery:null})))}
  if(path==='/api/admin/users'&&req.method==='GET'){const rows=await env.DB.prepare(`SELECT u.id,u.email,u.first_name,u.last_name,u.created_at,COUNT(o.id) orders FROM users u LEFT JOIN orders o ON o.user_id=u.id GROUP BY u.id ORDER BY u.created_at DESC`).all<any>();return json(req,env,rows.results.map(u=>({id:u.id,email:u.email,firstName:u.first_name,lastName:u.last_name,createdAt:u.created_at,_count:{orders:u.orders}})))}
  if(path==='/api/admin/audit-logs'&&req.method==='GET'){const rows=await env.DB.prepare('SELECT * FROM audit_logs ORDER BY created_at DESC LIMIT 250').all<any>();return json(req,env,rows.results.map(x=>({id:x.id,event:x.event,orderId:x.order_id,actor:x.actor,metadata:x.metadata?JSON.parse(x.metadata):null,createdAt:x.created_at})))}
  if(path==='/api/admin/deliveries'&&req.method==='GET')return json(req,env,[]);
  const review=path.match(/^\/api\/admin\/orders\/(\d+)\/(approve-payment|reject-payment)$/);if(review&&req.method==='POST'){const id=Number(review[1]),approve=review[2]==='approve-payment',existing=await env.DB.prepare('SELECT id,user_id,status FROM orders WHERE id=?').bind(id).first<any>();if(!existing)return json(req,env,{error:'Order not found'},404);if(existing.status!=='PAYMENT_REVIEW')return json(req,env,{error:'Order is not awaiting payment review'},409);const status=approve?'PAYMENT_APPROVED':'PAYMENT_REJECTED';await env.DB.prepare('UPDATE orders SET status=?,payment_reviewed_at=CURRENT_TIMESTAMP WHERE id=?').bind(status,id).run();await audit(env,status,id,existing.user_id,'admin');return json(req,env,{order:{id,status}})}
 }
 return json(req,env,{error:'API route not found'},404)
}
export default {async fetch(req:Request,env:Env){try{return await route(req,env)}catch(error){console.error(error);return json(req,env,{error:'Internal API error'},500)}}};
