export interface Env {
  DB:D1Database;
  ADMIN_API_KEY:string;
  ALLOWED_ORIGINS?:string;
  TRONGRID_API_KEY?:string;
}
type Json=Record<string,unknown>;
const FIXED_PAYMENT_WALLET='TGkSu19kCRFtZSWzZHduUcgESqcWQdfD6X';

function cors(req:Request,env:Env){const origin=req.headers.get('Origin')||'',allowed=(env.ALLOWED_ORIGINS||'https://alixbot85-source.github.io').split(',').map(x=>x.trim());return {'Access-Control-Allow-Origin':allowed.includes(origin)?origin:allowed[0],'Vary':'Origin','Access-Control-Allow-Headers':'Content-Type, Authorization, X-Admin-Key','Access-Control-Allow-Methods':'GET, POST, PUT, DELETE, OPTIONS','Access-Control-Max-Age':'86400'}}
function json(req:Request,env:Env,data:unknown,status=200){return new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store',...cors(req,env)}})}
async function body(req:Request){try{return await req.json() as Json}catch{return {}}}
function bytesToHex(bytes:Uint8Array){return [...bytes].map(x=>x.toString(16).padStart(2,'0')).join('')}
function randomToken(){const value=new Uint8Array(32);crypto.getRandomValues(value);return bytesToHex(value)}
async function passwordHash(password:string,salt:string){const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveBits']),bits=await crypto.subtle.deriveBits({name:'PBKDF2',hash:'SHA-256',salt:new TextEncoder().encode(salt),iterations:100000},key,256);return bytesToHex(new Uint8Array(bits))}
function isAdmin(req:Request,env:Env){const supplied=req.headers.get('x-admin-key')||'';return Boolean(env.ADMIN_API_KEY)&&supplied.length===env.ADMIN_API_KEY.length&&supplied===env.ADMIN_API_KEY}
async function currentUser(req:Request,env:Env){const token=(req.headers.get('Authorization')||'').replace(/^Bearer\s+/i,'');if(!token)return null;return env.DB.prepare(`SELECT u.id,u.email,u.first_name AS firstName,u.last_name AS lastName,u.role FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token=? AND s.expires_at>datetime('now') AND u.active=1`).bind(token).first<any>()}
async function audit(env:Env,event:string,orderId:number|null,userId:number|null,actor:string,metadata?:unknown){await env.DB.prepare('INSERT INTO audit_logs(event,order_id,user_id,actor,metadata) VALUES(?,?,?,?,?)').bind(event,orderId,userId,actor,metadata?JSON.stringify(metadata):null).run()}
function parse(value:string|null,fallback:unknown={}){try{return value?JSON.parse(value):fallback}catch{return fallback}}
function productDTO(row:any){return {id:row.id,legacyId:row.legacy_id,slug:row.slug,type:row.type,name:row.name,description:row.description,price:row.price,currency:row.currency,status:row.status,metadata:parse(row.metadata),sortOrder:row.sort_order,updatedAt:row.updated_at}}
async function lookupProduct(env:Env,type:string,legacyId:number){const normalized=type==='fund'?'resource':type;return env.DB.prepare(`SELECT * FROM products WHERE type=? AND legacy_id=? AND status='ACTIVE'`).bind(normalized,legacyId).first<any>()}

async function route(req:Request,env:Env){const url=new URL(req.url),path=url.pathname;
  if(req.method==='OPTIONS')return new Response(null,{status:204,headers:cors(req,env)});
  if(path==='/api/health')return json(req,env,{api:true,database:true,platform:'cloudflare-workers-d1',checkedAt:new Date().toISOString()});
  if(path==='/api/catalog'&&req.method==='GET'){const rows=await env.DB.prepare(`SELECT * FROM products WHERE status='ACTIVE' ORDER BY type,sort_order,id`).all<any>();return json(req,env,{products:rows.results.map(productDTO)});}
  if(path==='/api/settings/public'&&req.method==='GET'){const rows=await env.DB.prepare('SELECT key,value,updated_at FROM site_settings WHERE public=1').all<any>();return json(req,env,Object.fromEntries(rows.results.map(x=>[x.key,{...parse(x.value),updatedAt:x.updated_at}])));}
  if(path==='/api/payment-config'&&req.method==='GET')return json(req,env,{tronAddress:FIXED_PAYMENT_WALLET,usdtTrc20Address:FIXED_PAYMENT_WALLET,network:'TRC20'});

  if(path==='/api/auth/register'&&req.method==='POST'){const data=await body(req),email=String(data.email||'').trim().toLowerCase(),password=String(data.password||''),firstName=String(data.firstName||'').trim(),lastName=String(data.lastName||'').trim()||null;if(!email.includes('@')||password.length<8||!firstName)return json(req,env,{error:'Valid name, email, and password are required'},400);const salt=randomToken().slice(0,32),hash=await passwordHash(password,salt);try{const created=await env.DB.prepare('INSERT INTO users(email,first_name,last_name,password_hash,password_salt) VALUES(?,?,?,?,?) RETURNING id,email,first_name AS firstName').bind(email,firstName,lastName,hash,salt).first<any>(),token=randomToken(),expires=new Date(Date.now()+7*86400000).toISOString();await env.DB.prepare('INSERT INTO sessions(token,user_id,expires_at) VALUES(?,?,?)').bind(token,created.id,expires).run();await audit(env,'USER_REGISTERED',null,created.id,'user');return json(req,env,{user:created,token},201)}catch{return json(req,env,{error:'An account with this email may already exist'},409)}}
  if(path==='/api/auth/login'&&req.method==='POST'){const data=await body(req),email=String(data.email||'').trim().toLowerCase(),password=String(data.password||''),found=await env.DB.prepare('SELECT id,email,first_name AS firstName,last_name AS lastName,role,password_hash,password_salt FROM users WHERE email=? AND active=1').bind(email).first<any>();if(!found||await passwordHash(password,found.password_salt)!==found.password_hash)return json(req,env,{error:'Email or password is incorrect'},401);const token=randomToken(),expires=new Date(Date.now()+7*86400000).toISOString();await env.DB.prepare('INSERT INTO sessions(token,user_id,expires_at) VALUES(?,?,?)').bind(token,found.id,expires).run();return json(req,env,{user:{id:found.id,email:found.email,firstName:found.firstName,lastName:found.lastName,role:found.role},token});}
  if(path==='/api/auth/me'&&req.method==='GET'){const user=await currentUser(req,env);return user?json(req,env,{user}):json(req,env,{error:'Authentication required'},401);}
  if(path==='/api/auth/logout'&&req.method==='POST'){const token=(req.headers.get('Authorization')||'').replace(/^Bearer\s+/i,'');if(token)await env.DB.prepare('DELETE FROM sessions WHERE token=?').bind(token).run();return json(req,env,{signedOut:true});}

  if(path==='/api/orders'&&req.method==='GET'){const user=await currentUser(req,env);if(!user)return json(req,env,{error:'Authentication required'},401);const rows=await env.DB.prepare(`SELECT o.*,d.status delivery_status,d.scheduled_for,d.delivered_at FROM orders o LEFT JOIN deliveries d ON d.order_id=o.id WHERE o.user_id=? ORDER BY o.created_at DESC`).bind(user.id).all<any>();return json(req,env,rows.results.map(o=>({id:o.id,type:o.type,productName:o.product_name,price:o.price,status:o.status,paymentCurrency:o.payment_currency,txHash:o.tx_hash,configuration:parse(o.configuration),createdAt:o.created_at,delivery:o.delivery_status?{status:o.delivery_status,scheduledFor:o.scheduled_for,deliveredAt:o.delivered_at}:null})));}
  if(path==='/api/orders/submit-payment'&&req.method==='POST'){const user=await currentUser(req,env);if(!user)return json(req,env,{error:'Sign in before submitting a payment'},401);const data=await body(req),type=String(data.type||''),productId=Number(data.productId),currency=String(data.currency||''),txHash=String(data.txHash||'').trim().toLowerCase(),item=await lookupProduct(env,type,productId);if(!item||!['TRX','USDT_TRC20'].includes(currency)||!/^[a-f0-9]{64}$/.test(txHash))return json(req,env,{error:'Product, currency, or transaction hash is invalid'},400);const wallet=FIXED_PAYMENT_WALLET;try{const snapshot=JSON.stringify(productDTO(item)),created=await env.DB.prepare(`INSERT INTO orders(user_id,product_id,product_snapshot,type,product_name,price,status,payment_currency,payment_wallet,tx_hash,configuration) VALUES(?,?,?,?,?,?,'PAYMENT_REVIEW',?,?,?,?) RETURNING id,status`).bind(user.id,item.id,snapshot,item.type,item.name,item.price,currency,wallet,txHash,JSON.stringify(data.configuration||{})).first<any>();await audit(env,'PAYMENT_SUBMITTED',created.id,user.id,'user',{currency,txHash});return json(req,env,{order:created,status:'PAYMENT_REVIEW'},201)}catch{return json(req,env,{error:'This transaction hash has already been submitted'},409)}}

  const hashMatch=path.match(/^\/api\/blockchain\/tron\/transaction\/([a-fA-F0-9]{64})$/);if(hashMatch&&req.method==='GET'){const headers:Record<string,string>={'Content-Type':'application/json'};if(env.TRONGRID_API_KEY)headers['TRON-PRO-API-KEY']=env.TRONGRID_API_KEY;const hash=hashMatch[1].toLowerCase(),[txResponse,infoResponse]=await Promise.all(['gettransactionbyid','gettransactioninfobyid'].map(method=>fetch(`https://api.trongrid.io/wallet/${method}`,{method:'POST',headers,body:JSON.stringify({value:hash})})));if(!txResponse.ok||!infoResponse.ok)return json(req,env,{error:'TRON public API is unavailable'},503);const tx=await txResponse.json<any>(),info=await infoResponse.json<any>();if(!tx.txID)return json(req,env,{found:false,error:'Transaction was not found on TRON mainnet'},404);return json(req,env,{found:true,hash:tx.txID,confirmed:Boolean(info.blockNumber),blockNumber:info.blockNumber??null,timestamp:info.blockTimeStamp??tx.raw_data?.timestamp??null,networkResult:info.receipt?.result??tx.ret?.[0]?.contractRet??'INFORMATION NOT AVAILABLE',explorerUrl:`https://tronscan.org/#/transaction/${hash}`,source:'TRON Grid'});}

  if(path.startsWith('/api/admin/')){if(!isAdmin(req,env))return json(req,env,{error:'Admin authorization required'},403);
    if(path==='/api/admin/system-health'&&req.method==='GET')return json(req,env,{api:true,database:true,smtp:false,privateStorage:false,tronGrid:Boolean(env.TRONGRID_API_KEY),worker:true,platform:'Cloudflare Workers + D1',checkedAt:new Date().toISOString()});
    if(path==='/api/admin/products'&&req.method==='GET'){const rows=await env.DB.prepare('SELECT * FROM products ORDER BY type,sort_order,id').all<any>();return json(req,env,{products:rows.results.map(productDTO)});}
    if(path==='/api/admin/products'&&req.method==='POST'){const data=await body(req),type=String(data.type||''),name=String(data.name||'').trim(),price=Number(data.price),slug=String(data.slug||name.toLowerCase().replace(/[^a-z0-9]+/g,'-')).replace(/^-|-$/g,'');if(!['resource','server'].includes(type)||!name||!Number.isFinite(price)||price<0||!slug)return json(req,env,{error:'Valid product type, name, slug, and price are required'},400);const next=await env.DB.prepare('SELECT COALESCE(MAX(legacy_id),0)+1 next FROM products WHERE type=?').bind(type).first<any>();try{const row=await env.DB.prepare(`INSERT INTO products(slug,legacy_id,type,name,description,price,currency,status,metadata,sort_order) VALUES(?,?,?,?,?,?,?,?,?,?) RETURNING *`).bind(slug,next.next,type,name,String(data.description||''),price,String(data.currency||'USD'),String(data.status||'ACTIVE'),JSON.stringify(data.metadata||{}),Number(data.sortOrder||0)).first<any>();await audit(env,'PRODUCT_CREATED',null,null,'admin',{productId:row.id});return json(req,env,productDTO(row),201)}catch{return json(req,env,{error:'Product slug already exists'},409)}}
    const productMatch=path.match(/^\/api\/admin\/products\/(\d+)$/);if(productMatch&&req.method==='PUT'){const id=Number(productMatch[1]),data=await body(req),existing=await env.DB.prepare('SELECT * FROM products WHERE id=?').bind(id).first<any>();if(!existing)return json(req,env,{error:'Product not found'},404);const name=String(data.name??existing.name).trim(),price=Number(data.price??existing.price),status=String(data.status??existing.status);if(!name||!Number.isFinite(price)||price<0||!['ACTIVE','DRAFT','ARCHIVED'].includes(status))return json(req,env,{error:'Invalid product update'},400);const row=await env.DB.prepare(`UPDATE products SET name=?,description=?,price=?,currency=?,status=?,metadata=?,sort_order=?,updated_at=CURRENT_TIMESTAMP WHERE id=? RETURNING *`).bind(name,String(data.description??existing.description),price,String(data.currency??existing.currency),status,JSON.stringify(data.metadata??parse(existing.metadata)),Number(data.sortOrder??existing.sort_order),id).first<any>();await audit(env,'PRODUCT_UPDATED',null,null,'admin',{productId:id});return json(req,env,productDTO(row));}
    if(productMatch&&req.method==='DELETE'){const id=Number(productMatch[1]),used=await env.DB.prepare('SELECT COUNT(*) count FROM orders WHERE product_id=?').bind(id).first<any>();if(used?.count)return json(req,env,{error:'Ordered products must be archived instead of deleted'},409);await env.DB.prepare('DELETE FROM products WHERE id=?').bind(id).run();await audit(env,'PRODUCT_DELETED',null,null,'admin',{productId:id});return json(req,env,{deleted:true});}
    if(path==='/api/admin/site-settings'&&req.method==='GET'){const rows=await env.DB.prepare('SELECT key,value,public,updated_at FROM site_settings ORDER BY key').all<any>();return json(req,env,rows.results.map(x=>({key:x.key,value:parse(x.value),public:Boolean(x.public),updatedAt:x.updated_at})));}
    if(path==='/api/admin/site-settings'&&req.method==='PUT'){const data=await body(req),key=String(data.key||'').trim();if(!/^[a-z0-9_-]{2,50}$/i.test(key))return json(req,env,{error:'Invalid setting key'},400);await env.DB.prepare(`INSERT INTO site_settings(key,value,public,updated_at) VALUES(?,?,?,CURRENT_TIMESTAMP) ON CONFLICT(key) DO UPDATE SET value=excluded.value,public=excluded.public,updated_at=CURRENT_TIMESTAMP`).bind(key,JSON.stringify(data.value??{}),data.public?1:0).run();await audit(env,'SITE_SETTING_UPDATED',null,null,'admin',{key});return json(req,env,{key,value:data.value??{},public:Boolean(data.public)});}
    if(path==='/api/admin/payment-settings'&&req.method==='GET')return json(req,env,{tronAddress:FIXED_PAYMENT_WALLET,usdtTrc20Address:FIXED_PAYMENT_WALLET,network:'TRC20',editable:false});
    if(path==='/api/admin/payment-settings'&&req.method==='PUT')return json(req,env,{error:'Payment destinations are fixed in the deployed application.'},405);
    if(path==='/api/admin/orders'&&req.method==='GET'){const rows=await env.DB.prepare(`SELECT o.*,u.email,u.first_name,u.last_name,d.status delivery_status,d.attempts,d.scheduled_for,d.delivered_at FROM orders o JOIN users u ON u.id=o.user_id LEFT JOIN deliveries d ON d.order_id=o.id ORDER BY o.created_at DESC LIMIT 250`).all<any>();return json(req,env,rows.results.map(o=>({id:o.id,type:o.type,price:o.price,status:o.status,paymentCurrency:o.payment_currency,paymentWallet:o.payment_wallet,txHash:o.tx_hash,createdAt:o.created_at,user:{id:o.user_id,email:o.email,firstName:o.first_name,lastName:o.last_name},server:o.type==='server'?{name:o.product_name,protocol:'SERVER'}:undefined,fund:o.type==='resource'?{country:o.product_name,currency:'RESOURCE'}:undefined,delivery:o.delivery_status?{status:o.delivery_status,attempts:o.attempts,scheduledFor:o.scheduled_for,deliveredAt:o.delivered_at}:null})));}
    if(path==='/api/admin/users'&&req.method==='GET'){const rows=await env.DB.prepare(`SELECT u.id,u.email,u.first_name,u.last_name,u.role,u.active,u.created_at,COUNT(o.id) orders FROM users u LEFT JOIN orders o ON o.user_id=u.id GROUP BY u.id ORDER BY u.created_at DESC`).all<any>();return json(req,env,rows.results.map(u=>({id:u.id,email:u.email,firstName:u.first_name,lastName:u.last_name,role:u.role,active:Boolean(u.active),createdAt:u.created_at,_count:{orders:u.orders}})));}
    if(path==='/api/admin/audit-logs'&&req.method==='GET'){const rows=await env.DB.prepare('SELECT * FROM audit_logs ORDER BY created_at DESC LIMIT 250').all<any>();return json(req,env,rows.results.map(x=>({id:x.id,event:x.event,orderId:x.order_id,actor:x.actor,metadata:parse(x.metadata,null),createdAt:x.created_at})));}
    if(path==='/api/admin/deliveries'&&req.method==='GET'){const rows=await env.DB.prepare(`SELECT d.*,o.product_name,o.type FROM deliveries d JOIN orders o ON o.id=d.order_id ORDER BY d.created_at DESC`).all<any>();return json(req,env,rows.results.map(d=>({id:d.id,orderId:d.order_id,email:d.recipient_email,status:d.status,attempts:d.attempts,scheduledFor:d.scheduled_for,deliveredAt:d.delivered_at,order:{type:d.type,productName:d.product_name}})));}
    const review=path.match(/^\/api\/admin\/orders\/(\d+)\/(approve-payment|reject-payment)$/);if(review&&req.method==='POST'){const id=Number(review[1]),approve=review[2]==='approve-payment',data=await body(req),existing=await env.DB.prepare(`SELECT o.id,o.user_id,o.status,u.email FROM orders o JOIN users u ON u.id=o.user_id WHERE o.id=?`).bind(id).first<any>();if(!existing)return json(req,env,{error:'Order not found'},404);if(existing.status!=='PAYMENT_REVIEW')return json(req,env,{error:'Order is not awaiting payment review'},409);if(approve){const scheduledFor=new Date(Date.now()+2*60*60*1000).toISOString();await env.DB.batch([env.DB.prepare(`UPDATE orders SET status='DELIVERY_SCHEDULED',delivery_data=?,payment_reviewed_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(JSON.stringify(data.deliveryData||{}),id),env.DB.prepare(`INSERT INTO deliveries(order_id,recipient_email,status,scheduled_for) VALUES(?,?,'SCHEDULED',?)`).bind(id,existing.email,scheduledFor)]);await audit(env,'PAYMENT_APPROVED',id,existing.user_id,'admin',{scheduledFor});return json(req,env,{order:{id,status:'DELIVERY_SCHEDULED'},delivery:{status:'SCHEDULED',scheduledFor}});}await env.DB.prepare(`UPDATE orders SET status='PAYMENT_REJECTED',payment_reviewed_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(id).run();await audit(env,'PAYMENT_REJECTED',id,existing.user_id,'admin');return json(req,env,{order:{id,status:'PAYMENT_REJECTED'}});}
    if(path==='/api/admin/messages'&&req.method==='POST')return json(req,env,{error:'Email provider is not configured. Message was not sent.'},503);
  }
  return json(req,env,{error:'API route not found'},404);
}
export default {async fetch(req:Request,env:Env){try{return await route(req,env)}catch(error){console.error(error);return json(req,env,{error:'Internal API error'},500)}}};
