ALTER TABLE "Server" ADD COLUMN "pdfPath" TEXT, ADD COLUMN "emailSubject" TEXT, ADD COLUMN "emailBody" TEXT, ADD COLUMN "deliveryDelayHours" INTEGER NOT NULL DEFAULT 2;
ALTER TABLE "FundProduct" ADD COLUMN "pdfPath" TEXT, ADD COLUMN "emailSubject" TEXT, ADD COLUMN "emailBody" TEXT, ADD COLUMN "deliveryDelayHours" INTEGER NOT NULL DEFAULT 2;
ALTER TABLE "Order" ADD COLUMN "deliveryEmail" TEXT, ADD COLUMN "paymentApprovedAt" TIMESTAMP(3), ADD COLUMN "deliveryAt" TIMESTAMP(3);
CREATE TABLE "EmailDelivery" ("id" SERIAL PRIMARY KEY,"orderId" INTEGER NOT NULL UNIQUE,"userId" INTEGER NOT NULL,"email" TEXT NOT NULL,"pdfPath" TEXT NOT NULL,"emailSubject" TEXT NOT NULL,"emailBody" TEXT NOT NULL,"scheduledFor" TIMESTAMP(3) NOT NULL,"status" TEXT NOT NULL DEFAULT 'PENDING',"attempts" INTEGER NOT NULL DEFAULT 0,"lastAttemptAt" TIMESTAMP(3),"sentAt" TIMESTAMP(3),"errorMessage" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "AuditLog" ("id" SERIAL PRIMARY KEY,"event" TEXT NOT NULL,"orderId" INTEGER,"userId" INTEGER,"actor" TEXT NOT NULL,"metadata" JSONB,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX "AuditLog_orderId_createdAt_idx" ON "AuditLog"("orderId","createdAt");
ALTER TABLE "EmailDelivery" ADD CONSTRAINT "EmailDelivery_orderId_fkey" FOREIGN KEY ("orderId") REFERENCES "Order"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "AuditLog" ADD CONSTRAINT "AuditLog_orderId_fkey" FOREIGN KEY ("orderId") REFERENCES "Order"("id") ON DELETE SET NULL ON UPDATE CASCADE;
